"""add google calendar and meet columns to sessions

Revision ID: 8aed7fa66c83
Revises: ab0e10b1f17f
Create Date: 2026-09-07 11:20:36.471360+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aed7fa66c83'
down_revision: Union[str, None] = 'ab0e10b1f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_oauth_provider')
    )
    op.create_index(op.f('ix_user_oauth_accounts_provider'), 'user_oauth_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_user_oauth_accounts_user_id'), 'user_oauth_accounts', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('is_google_meet', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('google_meet_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_sessions_google_calendar_event_id'), 'sessions', ['google_calendar_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_google_calendar_event_id'), table_name='sessions')
    op.drop_column('sessions', 'google_meet_data')
    op.drop_column('sessions', 'is_google_meet')
    op.drop_column('sessions', 'google_calendar_event_id')
    op.drop_index(op.f('ix_user_oauth_accounts_user_id'), table_name='user_oauth_accounts')
    op.drop_index(op.f('ix_user_oauth_accounts_provider'), table_name='user_oauth_accounts')
    op.drop_table('user_oauth_accounts')
    # ### end Alembic commands ###
