"""create student_progress table

Revision ID: ab0e10b1f17f
Revises: cf582e087eb3
Create Date: 2026-09-07 09:23:43.460526+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0e10b1f17f'
down_revision: Union[str, None] = 'cf582e087eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('areas_to_improve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_focus', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_progress_profile_id', 'student_progress', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_student_progress_student_profile_id'), 'student_progress', ['student_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_progress_student_profile_id'), table_name='student_progress')
    op.drop_index('ix_student_progress_profile_id', table_name='student_progress')
    op.drop_table('student_progress')
    # ### end Alembic commands ###
