"""session model some column changed

Revision ID: cf582e087eb3
Revises: 7fc5718ab89d
Create Date: 2026-09-05 14:34:30.360265+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf582e087eb3'
down_revision: Union[str, None] = '7fc5718ab89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('meeting_url', sa.String(length=2048), nullable=True))
    op.drop_index(op.f('ix_sessions_scheduled_end'), table_name='sessions')
    op.drop_column('sessions', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_sessions_scheduled_end'), 'sessions', ['scheduled_end'], unique=False)
    op.drop_column('sessions', 'meeting_url')
    # ### end Alembic commands ###
